### PR TITLE
refactor: External Ids schema

### PR DESCRIPTION
**Pull request by fcibecchini**
Example value:
```
{
  ...,
  "stories": [
    {
      ...,
      "entities": [
        {
          ...,
          "external_ids": {
            "duns": [
              {
                "id": "string"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Comment by FrontSide** [comment]
LGTM (though I'm conceptually not a big fan of this change, but I guess if it's required for search)

**Review by FrontSide — APPROVED** [review]

**Comment by marcinaylien** [comment]
@fcibecchini can't we use a dictionary/map? https://swagger.io/docs/specification/data-models/dictionaries/

**Comment by fcibecchini** [comment]
> @fcibecchini can't we use a dictionary/map? https://swagger.io/docs/specification/data-models/dictionaries/

Yes, but I would prefer to keep the external domains types explicit, in case we add another domain that has different properties (something more than an ID for instance). That's why `duns` is of type `Array<DunsNumber>`. 
Do you think I'm overthinking this and should rather keep everything generic?

**Comment by marcinaylien** [comment]
@fcibecchini we can just have ExternalId and use polymorphism if we want to add a new field :)

**Comment by marcinaylien** [comment]
But I am not sure how the plugin that we use will handle all that generic things. We can keep things simple for now

**Pull request merged**
